version: "3.7"

networks:
  es-network:

services:
  elasticsearch-plugin-debug:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: elasticsearch-plugin-debug
    environment:
      - discovery.type=single-node
      # NO DEBUG
      # - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # DEBUG
      - ES_JAVA_OPTS=-Xms512m -Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
    ports:
      - "9200:9200"
      # DEBUG
      - "5005:5005"
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch-plugin-debug:9200/
    ports:
      - "5602:5601"
    networks:
      - es-network
